### ISSUE TITLE
No Schedule tab found after those steps

### ISSUE THREAD

**Issue by leetom** [kenorb/booking_timeslots#11]
Hi, I installed this module and followed the README file, but I cannot see the 'Schedule' tab as described in step 9.

I have grant all permissions related to this module.

Where did I do wrong?

**Comment by kenorb** [comment]
You can try to install the site demo available at: https://github.com/mycognitive/booking_timeslots_example_site
and follow the steps described there by installing the site using the script, it'll be the easiest way. And then compare what could be missing. Some of the dependent contrib modules had some changes and could be some compability issue.

See also: https://www.drupal.org/node/2288771

**Comment by kenorb** [comment]
Fixed.
